[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meteomat"
version = "0.1.0"
description = "Probabilistic rainfall forecasts for Europe with ensemble uncertainty visualization "
authors = [{name = "Pablo Matorras-Cuevas", email = "pablo.matorras@github.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # Note: torch, torchvision, torchaudio must be installed separately
    # See README for GPU vs CPU installation instructions
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"