[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meteomat"
version = "2.2.1"
description = "Probabilistic rainfall forecasts for Europe with ensemble uncertainty visualization "
authors = [{name = "Pablo Matorras-Cuevas", email = "pablo.matorras@github.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.1.0",
    "matplotlib>=3.7.0",
    "plotly",
    "folium",
    "streamlit",
    "streamlit-folium",
    "python-telegram-bot>=20.0",
    "kaleido",
    "shapely",
    "pyproj",
]
[project.optional-dependencies]
train = [ 
    "cdsapi",
    "xarray",
    "zarr",
    "fsspec",
    "aiohttp",
    "requests",
    "gcsfs",
    "dask",
    "netcdf4",
    "h5netcdf",
    "h5py",
    ]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
"meteomat.viz.assets" = ["smart_ticks.js"]
